name: A workflow for my Hello World file
on:
  push:
##  schedule:
##    - cron:  '45 * * * *'

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v1
      - name: print-to-file
        uses: ./action-a
        with:
          MY_NAME: "Liza"
      - name: upload-file
        uses: actions/upload-artifact@v2
        with:
          name: greetings-file
          path: greetings.txt
      - name: download-file
        uses: actions/download-artifact@v2
        with:
          name: greetings-file
        needs: upload-file
